### ISSUE TITLE
Tracking for support plan replayer in diag 

### ISSUE THREAD

**Issue by Yisaer** [pingcap/diag#338]
## Feature Request

support plan replayer in diag:

* [x] sql binding https://github.com/pingcap/diag/pull/333
* [x] results for explaining sqls https://github.com/pingcap/diag/pull/342
* [x] table statistics https://github.com/pingcap/diag/pull/337
* [x] table structures https://github.com/pingcap/diag/pull/355
* [x] support scenario param  https://github.com/pingcap/diag/pull/359 #360 #375
